class FourMomentum:
    def __init__(self, e: float, px: float, py: float, pz: float) -> None: ...
    def e(self) -> float: ...
    def px(self) -> float: ...
    def py(self) -> float: ...
    def pz(self) -> float: ...
    def set_e(self, value: float) -> None: ...
    def set_px(self, value: float) -> None: ...
    def set_py(self, value: float) -> None: ...
    def set_pz(self, value: float) -> None: ...
    def m2(self) -> float: ...
    def m(self) -> float: ...
    def boost_along(self, other: FourMomentum) -> float: ...
