from rustitude import Amplitude, Amplitude_64, Amplitude_32

def OmegaDalitz(name: str, decay: str = '[0, 1, 2]') -> Amplitude: ...
def OmegaDalitz_64(name: str, decay: str = '[0, 1, 2]') -> Amplitude_64: ...
def OmegaDalitz_32(name: str, decay: str = '[0, 1, 2]') -> Amplitude_32: ...
