name: Benchmarks

on:
  pull_request:
    branches: ["main"]

jobs:
  bench:
    name: Criterion Compare PRs
    runs-on: ubuntu-latest
    steps:
      - uses: boa-dev/criterion-compare-action@v3.2.4
